### ISSUE TITLE
no reference for REDIS_CACHE_HOST

### ISSUE THREAD

**Issue by lethargosapatheia** [CENGN/netbox-kubernetes#4]
Hello,

You're not referencing `REDIS_CACHE_HOST` in the configmap, so when you deploy it netbox, it doesn't work.

**Comment by mohahmed13** [comment]
Hi @lethargosapatheia , I think it is mentioned here: https://github.com/CENGN/netbox-kubernetes/blob/master/netbox-deployment.yaml#L108 

Let me know if you think that's missing. I will just note that there's a better way to do this by referencing all values from a ConfigMap using the envFrom spec: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#environment-variables. We have future plans to upgrade these manifests and share it with the community.

**Comment by lethargosapatheia** [comment]
Thanks for replying. I must have missed it, I'm not sure why.

Regarding the `envFrom` spec - doesn't netbox expect the variables to be read from /run/secrets? I'm not sure how you can mount the volumes which you reference in the `envFrom`.

**Comment by mohahmed13** [comment]
Ah yeah, I meant that with the `envFrom` spec, all values in the ConfigMap would be mounted as environment variables automatically. That would eliminate the need to do this for every environment variable:
```
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              key: ALLOWED_HOSTS
              name: netbox-configmap
```

For the /run/secrets, like you said, you would still need to mount them as volumes.
